### PR TITLE
[Fix] use `has`; make <= 0.8 work

### LINKED ISSUE #2: breaks in node 0.8
It seems `process.env.hasOwnProperty` fails in node 0.8.

If you use the `has` package, then it will work everywhere. PR incoming.

### PR DESCRIPTION
**Pull request by ljharb**
Fixes #2.

### CODE REVIEW

**Comment by ljharb** [comment]
This PR also adds testing on a bunch more node versions.

**Comment by ljharb** [comment]
@burl Thanks‼!

**Comment by burl** [comment]
I'll release a new version on NPM in a while

**Comment by ljharb** [comment]
Much obliged :-)

**Comment by ljharb** [comment]
@burl any update on a publish?

**Comment by burl** [comment]
@ljharb it is now [published](https://www.npmjs.com/package/mock-env) - sorry for the delay

**Comment by ljharb** [comment]
@burl thank you, it's much appreciated!!

**Pull request merged**
